# Generated by Django 2.0.5 on 2019-04-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedate',
            name='ff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedate',
            name='imp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedate',
            name='isc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedate',
            name='max_system_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedate',
            name='pmp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedate',
            name='vmp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancedate',
            name='voc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
