# Generated by Django 2.0.5 on 2019-04-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190418_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerformanceDate',
            new_name='PerformanceData',
        ),
    ]
