# Generated by Django 2.0.5 on 2019-04-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190418_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='userID',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='backend.User', to_field='userID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.CharField(max_length=20),
        ),
    ]
