# Generated by Django 2.0.5 on 2019-04-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190418_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='model_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product', to_field='model_number'),
        ),
    ]
