# Generated by Django 2.2 on 2019-04-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ID', models.CharField(max_length=10, unique=True)),
                ('client_name', models.CharField(max_length=40)),
                ('client_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_ID', models.CharField(max_length=10, unique=True)),
                ('standard_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('published_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client', to_field='client_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_ID', models.CharField(max_length=10, unique=True)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('fax_number', models.CharField(max_length=50)),
                ('client_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client', to_field='client_ID')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('model_number', models.CharField(max_length=50)),
                ('certificate_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Product', to_field='model_number')),
                ('location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Location', to_field='location_ID')),
                ('standard_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.TestStandard', to_field='standard_ID')),
            ],
        ),
    ]
