# Generated by Django 2.0.5 on 2019-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
